### ISSUE TITLE
Block style toggling

### ISSUE THREAD

**Issue by seandunn** [otavioschwanck/ruby-toolkit.nvim#1]
Add treesitter based block style togging from `{ ... }` to `do ... end`.

Similar behaviour can be found in https://github.com/jgdavey/vim-blockle (but without Treesitter support).

**Comment by otavioschwanck** [comment]
> 

For that, you can use https://github.com/AndrewRadev/splitjoin.vim.  It work with another languages as well.

**Comment by seandunn** [comment]
That's a great point. Sorry, I'd forgotten about splitjoin, even though I actually used it for years in a previous config.
